language: swift
osx_image: xcode10

before_install:
- bash decryptCertificates.sh

install:
- bash install_swiftlint.sh

before_script:
- bash travis-scripts/add-keys.sh
- bash travis-scripts/update-bundle.sh

script:
- pod install
- swiftlint
- bash build.sh
- bash validateCoverage.sh

after_script:
- bash travis-scripts/delete-keys.sh

after_success:
- bash generateIPA.sh
- bash travis-scripts/ipa-upload.sh

env:
global:
- bash set-environment.sh
