language: swift
osx_image: xcode10

install:
- ./install_swiftlint.sh

script:
- pod install
- swiftlint
- xcodebuild -workspace travis-ci-ex.xcworkspace -scheme travis-ci-ex -derivedDataPath Build/ -destination 'platform=iOS Simulator,OS=12.0,name=iPhone 7' -enableCodeCoverage YES clean build test
- bash logCoverage.sh
