language: swift
osx_image: xcode10

ts="travis-scripts"
before_install:
- bash $ts/decryptCertificates.sh

install:
- bash travis-scripts/install_swiftlint.sh

before_script:
- bash travis-scripts/add-keys.sh
- bash travis-scripts/update-bundle.sh

script:
- pod install
- swiftlint
- bash travis-scripts/build.sh
- bash travis-scripts/validateCoverage.sh

after_script:
- bash travis-scripts/delete-keys.sh

after_success:
- bash travis-scripts/generateIPA.sh
- bash travis-scripts/ipa-upload.sh

env:
global:
- bash travis-scripts/set-environment.sh
