language: swift
osx_image: xcode10

before_install:
- openssl aes-256-cbc -k "password" -in dist.p12.enc -d -a -out dist.p12
- openssl aes-256-cbc -k "password" -in dist.cer.enc -d -a -out dist.cer
- openssl aes-256-cbc -k "password" -in dist.mobileprovision.enc -d -a -out dist.mobileprovision

install:
- ./install_swiftlint.sh

before_script:
- ./travis-scripts/add-keys.sh
- ./travis-scripts/update-bundle.sh

script:
- pod install
- swiftlint
- xcodebuild -workspace travis-ci-ex.xcworkspace -scheme travis-ci-ex -derivedDataPath BuildFolder/ -destination 'platform=iOS Simulator,OS=12.0,name=iPhone 7' -enableCodeCoverage YES clean build test
- xcodebuild -workspace travis-ci-ex.xcworkspace -scheme travis-ci-ex -sdk iphoneos -configuration Release -derivedDataPath build/ -archivePath ArchiveFolder/travis-ci-ex.xcarchive PROVISIONING_PROFILE="dist.mobileprovision" ONLY_ACTIVE_ARCH=NO archive
- bash validateCoverage.sh

after_script:
- ./travis-scripts/delete-keys.sh

after_success:
- xcodebuild -exportArchive -archivePath ArchiveFolder/travis-ci-ex.xcarchive -exportOptionsPlist "ExportOptions.plist" -exportPath IPA
- ./travis-scripts/ipa-upload.sh

env:
global:
- secure: MxPj9C/6/pDZYFsRJemt3KQ6iGF2/qYWxGOj4b5zz7XRVPFDY1uHE4Tkdalo/phmMYTwrebpNiUYqAGoV1JuqoyZKMuP3p+Rhjvkak0jUW7KwKY+FrW1SvJQL0B7DdFldeFYsFP+lsfSozRpXFOLwt8cocDuZoNY/f0AeZklvAhoBKQoyqX9Xl1ZfIdyINbITrEq76zA6hC9uTEI1HUh2y3orw/Fq7YFjS0eTImGwop8L7e8TTC2psql/riJyrkr7p74nBrtFP68CN0AkVUvjQEnlz8dBkiiRiZwzb4lzdKGW6kxAcjve/nUn+I6X6q1bd/kIQ0bUrCNunaHVtZIq5AklvicqMKySms9HVVofJFgbloH+i/unhSu2yWx7/jzrzTw4/ZFDizhKwXXLTaO3I2+Tvuendes1i14pDoIOkwy1uBcWmFcNUV/G/wU1LJVKO4NTI1iDp7RM79m79PCX8S8gxF/zyGC0Dy7ROibclwjCglZxs1rF74wg/5j1sJpb62xMDtpUoq0gHKtGcvt1URqraobBrvzHpnzDjeEq5ewBPOSEfv9h7PZFPCQny4dRbnx0fYulngfF2xHGhvCQT7EOIhgqtFrbzAtIcPMpvtOAAfh/H+6J7lsjnNms53ALt3/y+WbEK9kJnXzmfEl64I3QJ15JUXTI6mEAfc09jQ=
- secure: "hsWyacTwJVwfqZKu7g6VuAg4e7BT15nYbPLvHWgY6rRdpVu/VpX49o5MdWMpQA1ZQaAu6cLySqlRRNWm6QZZy41MCvzPiaZ41Yx7RNpXbuzgNXMaN3zTb6u1tE8s+p5PKHgSmq5+Jj0ngR3SeI2al7n+p3bdvRJnIvQwoLejgJMg5AVc9OUyazVGD+72PEQ+irhCISdp1NmhGzWEgdMWOF2EzuAnVE7+my+zTkiyTPyMI4cq8/MZ+JVzonPC5t8S7Ymjpc37J9GQgNFjrZYEENoMZsmOZ601FmozTXEBQ/hpuglpa6bx7ERt4oJRsKWEKuG+pyo1CgjDKIYDYQQd4bpSInlZofBp5YtnCDT8bV3Ll5xeJfc9Wfq026GKfmNRMAHUJRFHpHZvIA4PcIL1kad5pSGQOMPNDemxwdjgRh0tWjSw3/+M0Ru20us0Z/zOHGxFfzJUxrQ2tOjFZVKm1YWqW0lTZp3PK4IbC9dt8iEQ1EixMvjB8H13wUX1oIdeqo4hb2bCmjzE9WGFZAxaXr36k/Jhw+qlS5ZVKKw+E7j2xaJcLBpV4t8wVP45qpUTZ9xNxTkPqITqfFCqDjWq83piJlfoIwhNx9cp2yV3fl/NppAw8KrXOTNWGAX7hgv9885ig6Melkmt/1BrkyM273DdZ/+hTbngorWKCnRoIEc="
- secure: "O7PwDfYUWAynqIMspu6qwHa2Iahoy7+Vf0ohRYzqwM7yStsDgSlC2ndGh6fDffQSkC2MeOJ9T0FkubuklKili42/iQTTqH16uahSf4dS7pBJ3c8U5cMuAgSEygQdv+ItRyhXRx57rszdxwIKxtBcAa1AsSOQOPZv2smQUs06vyuzP31Xdcsk09XKx0oKmugRCW7H4njFmF0Zco7QxUudLJZ05/fZ5OsoDreRabKb+bZlans3EyhXNvnMi0TqtLizIkBiGeyL+YxsSa2AQTfX6zo9bH1/JGJ+I+4uOhJzCt0YXB7QjrbR2rsRn8UvPv0JGSzQXDmGlMn44Ma7JTnrhx5L3kfL47ovzXVqQlsIgf3OZWd0LctMpNEi1ACg/QePuDZ6CVZbHpjzJ5iixqOpVY2RKuxCMZ9aZ0Iwhy0Cb54pM/kegPudy00DKbkeUWOLTKCvwsEOUqVj81nCCBOgHgFxH+BniMndM6OQAdMtfQqg1WIBzq06szYJcXsM2aC29QW2OgPFI1fxkW2c0ctMSKOWtwYlUcjwFF1U7qoRgf+AgcE4I4NOh+Wu3Q5/scByotd4FuhuouEBOftuG0Y0jv9iT+BIqOupF6uT5cVWFuy0BXRdGuFgWW9uU9lb3hhiYlYHPA9jC/ikq2JfMzLVMfFBlZY6e7Fp337lFYkLWNM="
- APP_NAME="travis-ci-ex"
- XCODE_SCHEME="travis-ci-ex"
- UNIT_TEST_SCHEME="travis-ci-exTests"
- 'DEVELOPER_NAME="iOS Distribution: EduKitten Ltd"'
- PROJECT_DIRECTORY="/"
- SCRIPT_FOLDER="travis-scripts"
- CERT_FOLDER="ios-certs"
- INFO_PLIST="travis-ci-ex/Info.plist"
