codecov:
  branch: master  # override the default branch
  notify: # ADVANCED USE ONLY
    after_n_builds: null      # number of expected builds to recieve before sending notifications
                              # after: check ci status unless disabled via require_ci_to_pass
    require_ci_to_pass: yes   # yes: will delay sending notifications until all ci is finished
                              # no: will send notifications without checking ci status and wait till "after_n_builds" are uploaded
    countdown: null           # number of seconds to wait before first ci build check
    delay: null               # number of seconds to wait between ci build checks

coverage:
  precision: 2  # 2 = xx.xx%, 0 = xx%
  round: down|up|nearest # default down
  range: 50...60 # default 70...90. red...green

  status:
    project:
      default:
        against: parent
        target: auto
        threshold: 1%
        branches:
          - master
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder

    patch:
      default:
        against: parent
        target: 80%
        branches: null
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder
    
    changes:
      default:
        against: parent
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder

  flags:
    integration:
      branches:
        - master
      ignore:
        - app/ui

  ignore: # files and folders for processing
    - tests/*
  
  fixes:
    - "old_path::new_path"

comment:
  layout: header, diff, trends, uncovered
  branches: *
  behavior: default # defualt = posts once then update, posts new if delete
                    # once = post once then updates
                    # new = delete old, post new
                    # spammy = post new
