codecov:
    notify:
        require_ci_to_pass: yes

coverage:
    round: down
    range: 80...100
    status:
        project:
            default: false
            tests:
                target: 80%
